name: spigot-plugin-test
version: 1.0.0
author: Michal
main: com.github.mkorman9.spigotplugintest.Entrypoint
api-version: 1.17
commands:
  schedulepoweroff:
    description: Stops server and shuts down the machine once all players log out
    usage: /schedulepoweroff
