name: utility-plugin
version: 1.0.0
description: Simple plugin providing basic utilities for server management
author: Michal
main: com.github.mkorman9.spigotplugintest.Entrypoint
api-version: 1.17

commands:
  poweroffwhenempty:
    description: Stops server and shuts down the machine once all players log out
    usage: /poweroffwhenempty
    permission: utilityplugin.poweroff
    permission-message: You do not have the required permissions to execute this command
    aliases:
      - powe
  poweroffin:
    description: Stops server and shuts down the machine at specific time
    usage: /poweroffin <minutes>
    permission: utilityplugin.poweroff
    permission-message: You do not have the required permissions to execute this command
    aliases:
      - poi

permissions:
  utilityplugin.poweroff:
    description: Allows to execute poweroff related commands
    default: false
